# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
   include:
     - master



pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.x'
  inputs:
    packageType: 'sdk'
    version: '2.x'
    includePreviewVersions: true

- task: SonarCloudPrepare@1
  displayName: SonarCloudPrep
  inputs:
    SonarCloud: 'sonarCloud'
    organization: '2011-nov02-net'
    scannerMode: 'MSBuild'
    projectKey: '2011-nov02-net_mattm-project1'
    projectName: 'mattm-project1'
    extraProperties: 'sonar.exclusions=**/lib/**'

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.x'
  inputs:
    packageType: 'sdk'
    version: '5.x'
    includePreviewVersions: true

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: AcmeWebStore/AcmeWebStore

- task: SonarCloudAnalyze@1


- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
    workingDirectory: AcmeWebStore/AcmeWebStore

- script: dotnet publish --configuration $(buildConfiguration) --output publish
  displayName: 'dotnet publish $(buildConfiguration)'
  workingDirectory: AcmeWebStore/AcmeWebStore



- task: AzureRmWebAppDeployment@4
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (a7c7be2b-dec9-4b29-b6aa-d73e6d6ad223)'
    appType: 'webApp'
    WebAppName: 'AnotherTestWebApp'
    packageForLinux: 'AcmeWebStore/AcmeWebStore/publish'

